### ISSUE TITLE
hi ，能否实现一个mp4中随意位置插入一个短音效，进行混音

### ISSUE THREAD

**Issue by songdings** [YeDaxia/MusicPlus#2]
hi ，能否实现一个mp4中随意位置插入一个短音效，进行混音

**Comment by Knight-ZXW** [comment]
@songdings  您在 mp4 和 音乐混音时，不同比特率之类的情况下，怎么处理的

**Comment by CodeK1988** [comment]
MP4parser 以及ffmpeg 转码比较快 也能实现 但是 我想请教的是 混音的时候 比较耗时 怎么处理

**Comment by YeDaxia** [comment]
@yizuochengchi 转码得到原生数据后，然后拆分数据，分多条线程来混音，最后合并。不过文件的操作会增加不少，你可以试一下。

**Comment by CodeK1988** [comment]
你的意思是 转成pcm然后做指定位置插入的操作？ 我音频这块之前没接触过 不是太明白 。 谢谢~

**Comment by YeDaxia** [comment]
@yizuochengchi 转成pcm数据之后，你可以拆分多段混音，只要保证和原来的顺序一致即可。

**Comment by CodeK1988** [comment]
也只好如此了 拆分的话 会比较繁琐 而 ffmpeg 的 amix adelay 又比较耗时 。。。 不过还是 谢谢你的回答

**Comment by CodeK1988** [comment]
请教一下 在mp4的指定位置插入 一段pcm 替换原来位置的 可以做到吗？ 可以给个建议吗？ 谢谢 ~

**Comment by YeDaxia** [comment]
@yizuochengchi 首先肯定是可以做到的，mp4分离出视频轨和音轨之后，你按照码率来算出某段时间内应该裁剪的字节数，然后把你那段相同字节的pcm替换过去，最后重新编码成mp4格式应该就可以了。

**Comment by CodeK1988** [comment]
我今天看你的代码   试了一天  请问 DecodeEngine.getInstance().beginDecodeMusicFile 这个 方法 可以处理指定位置插入 替换吗？ 我试着 DecodeEngine.getInstance().beginDecodeMusicFile(musicPath, pcmPath, play_begin/1000, (play_end-play_begin)/1000+2,
            this);  得到的文件 是一片噪音。
